# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ssmes.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.term = None
        self.data = None
        self.courses = None
        self.departments = None
        self.number_random_trials = 5
        self.random_seed = 42

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1149, 690)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.RestrictedSplitDepartmentsLabel = QtWidgets.QLabel(self.centralwidget)
        self.RestrictedSplitDepartmentsLabel.setObjectName("RestrictedSplitDepartmentsLabel")
        self.gridLayout.addWidget(self.RestrictedSplitDepartmentsLabel, 13, 5, 1, 1)
        self.FromExcludedButton = QtWidgets.QPushButton(self.centralwidget)
        self.FromExcludedButton.setObjectName("FromExcludedButton")
        self.gridLayout.addWidget(self.FromExcludedButton, 3, 4, 1, 1)
        self.ExcludedCoursesLabel = QtWidgets.QLabel(self.centralwidget)
        self.ExcludedCoursesLabel.setObjectName("ExcludedCoursesLabel")
        self.gridLayout.addWidget(self.ExcludedCoursesLabel, 1, 5, 1, 1)
        self.DataFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.DataFileButton.setMinimumSize(QtCore.QSize(0, 40))
        self.DataFileButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.DataFileButton.setObjectName("DataFileButton")
        self.gridLayout.addWidget(self.DataFileButton, 5, 1, 1, 1)
        self.DataFileLabel = QtWidgets.QLabel(self.centralwidget)
        self.DataFileLabel.setObjectName("DataFileLabel")
        self.gridLayout.addWidget(self.DataFileLabel, 4, 0, 1, 1)
        self.FromRestrictedButton = QtWidgets.QPushButton(self.centralwidget)
        self.FromRestrictedButton.setObjectName("FromRestrictedButton")
        self.gridLayout.addWidget(self.FromRestrictedButton, 15, 4, 1, 1)
        self.CheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBox.setObjectName("CheckBox")
        self.gridLayout.addWidget(self.CheckBox, 16, 5, 1, 1)
        self.CoursesListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.CoursesListWidget.setObjectName("CoursesListWidget")
        self.gridLayout.addWidget(self.CoursesListWidget, 2, 3, 6, 1)
        self.NumberOfExamDaysTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.NumberOfExamDaysTextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.NumberOfExamDaysTextEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.NumberOfExamDaysTextEdit.setObjectName("NumberOfExamDaysTextEdit")
        self.gridLayout.addWidget(self.NumberOfExamDaysTextEdit, 7, 0, 1, 3)
        self.RestrictedSplitDepartmentsListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.RestrictedSplitDepartmentsListWidget.setObjectName("RestrictedSplitDepartmentsListWidget")
        self.gridLayout.addWidget(self.RestrictedSplitDepartmentsListWidget, 14, 5, 2, 3)
        self.ToDefiniteButton = QtWidgets.QPushButton(self.centralwidget)
        self.ToDefiniteButton.setObjectName("ToDefiniteButton")
        self.gridLayout.addWidget(self.ToDefiniteButton, 11, 4, 1, 1)
        self.ExcludedCoursesLoadFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExcludedCoursesLoadFileButton.setMinimumSize(QtCore.QSize(90, 40))
        self.ExcludedCoursesLoadFileButton.setMaximumSize(QtCore.QSize(5, 40))
        self.ExcludedCoursesLoadFileButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ExcludedCoursesLoadFileButton.setObjectName("ExcludedCoursesLoadFileButton")
        self.gridLayout.addWidget(self.ExcludedCoursesLoadFileButton, 9, 7, 1, 1)
        self.DefiniteSplitDepartmentsLabel = QtWidgets.QLabel(self.centralwidget)
        self.DefiniteSplitDepartmentsLabel.setObjectName("DefiniteSplitDepartmentsLabel")
        self.gridLayout.addWidget(self.DefiniteSplitDepartmentsLabel, 10, 5, 1, 1)
        self.TermListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.TermListWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.TermListWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.TermListWidget.setObjectName("TermListWidget")
        self.gridLayout.addWidget(self.TermListWidget, 2, 0, 2, 3)
        self.FromDefiniteButton = QtWidgets.QPushButton(self.centralwidget)
        self.FromDefiniteButton.setObjectName("FromDefiniteButton")
        self.gridLayout.addWidget(self.FromDefiniteButton, 12, 4, 1, 1)
        self.MessageCenterTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MessageCenterTextEdit.setEnabled(True)
        self.MessageCenterTextEdit.setReadOnly(True)
        self.MessageCenterTextEdit.setObjectName("MessageCenterTextEdit")
        self.gridLayout.addWidget(self.MessageCenterTextEdit, 9, 0, 7, 3)
        self.LoadDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadDataButton.setMinimumSize(QtCore.QSize(0, 40))
        self.LoadDataButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.LoadDataButton.setObjectName("LoadDataButton")
        self.gridLayout.addWidget(self.LoadDataButton, 5, 2, 1, 1)
        self.ExcludedCoursesFileLabel = QtWidgets.QLabel(self.centralwidget)
        self.ExcludedCoursesFileLabel.setObjectName("ExcludedCoursesFileLabel")
        self.gridLayout.addWidget(self.ExcludedCoursesFileLabel, 8, 5, 1, 1)
        self.ExcludedCoursesFileTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ExcludedCoursesFileTextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.ExcludedCoursesFileTextEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ExcludedCoursesFileTextEdit.setObjectName("ExcludedCoursesFileTextEdit")
        self.gridLayout.addWidget(self.ExcludedCoursesFileTextEdit, 9, 5, 1, 1)
        self.CoursesLabel = QtWidgets.QLabel(self.centralwidget)
        self.CoursesLabel.setObjectName("CoursesLabel")
        self.gridLayout.addWidget(self.CoursesLabel, 1, 3, 1, 1)
        self.DepartmentsLabel = QtWidgets.QLabel(self.centralwidget)
        self.DepartmentsLabel.setObjectName("DepartmentsLabel")
        self.gridLayout.addWidget(self.DepartmentsLabel, 8, 3, 1, 1)
        self.DefiniteSplitDepartmentsListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.DefiniteSplitDepartmentsListWidget.setObjectName("DefiniteSplitDepartmentsListWidget")
        self.gridLayout.addWidget(self.DefiniteSplitDepartmentsListWidget, 11, 5, 2, 3)
        self.TermLabel = QtWidgets.QLabel(self.centralwidget)
        self.TermLabel.setObjectName("TermLabel")
        self.gridLayout.addWidget(self.TermLabel, 1, 0, 1, 1)
        self.NumberOfExamDaysLabel = QtWidgets.QLabel(self.centralwidget)
        self.NumberOfExamDaysLabel.setObjectName("NumberOfExamDaysLabel")
        self.gridLayout.addWidget(self.NumberOfExamDaysLabel, 6, 0, 1, 1)
        self.DataFileTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.DataFileTextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.DataFileTextEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.DataFileTextEdit.setObjectName("DataFileTextEdit")
        self.gridLayout.addWidget(self.DataFileTextEdit, 5, 0, 1, 1)
        self.ExcludedCoursesListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ExcludedCoursesListWidget.setObjectName("ExcludedCoursesListWidget")
        self.gridLayout.addWidget(self.ExcludedCoursesListWidget, 2, 5, 6, 3)
        self.ToExcludedButton = QtWidgets.QPushButton(self.centralwidget)
        self.ToExcludedButton.setObjectName("ToExcludedButton")
        self.gridLayout.addWidget(self.ToExcludedButton, 2, 4, 1, 1)
        self.ToRestrictedButton = QtWidgets.QPushButton(self.centralwidget)
        self.ToRestrictedButton.setObjectName("ToRestrictedButton")
        self.gridLayout.addWidget(self.ToRestrictedButton, 14, 4, 1, 1)
        self.CreateExamScheduleButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreateExamScheduleButton.setObjectName("CreateExamScheduleButton")
        self.gridLayout.addWidget(self.CreateExamScheduleButton, 16, 0, 1, 3)
        self.DepartmentsListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.DepartmentsListWidget.setObjectName("DepartmentsListWidget")
        self.gridLayout.addWidget(self.DepartmentsListWidget, 9, 3, 7, 1)
        self.MessageCenterLabel = QtWidgets.QLabel(self.centralwidget)
        self.MessageCenterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MessageCenterLabel.setObjectName("MessageCenterLabel")
        self.gridLayout.addWidget(self.MessageCenterLabel, 8, 0, 1, 3)
        self.SSMESLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.SSMESLabel.setFont(font)
        self.SSMESLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SSMESLabel.setObjectName("SSMESLabel")
        self.gridLayout.addWidget(self.SSMESLabel, 0, 0, 1, 8)
        self.ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setObjectName("ProgressBar")
        self.gridLayout.addWidget(self.ProgressBar, 16, 3, 1, 1)
        self.ExcludedCoursesFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExcludedCoursesFileButton.setMinimumSize(QtCore.QSize(0, 40))
        self.ExcludedCoursesFileButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ExcludedCoursesFileButton.setObjectName("ExcludedCoursesFileButton")
        self.gridLayout.addWidget(self.ExcludedCoursesFileButton, 9, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1149, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #self.actionSave_As = QtWidgets.QAction(MainWindow)
        #self.actionSave_As.setObjectName("actionSave_As")
        #self.actionSave = QtWidgets.QAction(MainWindow)
        #self.actionSave.setObjectName("actionSave")
        #self.actionOpen = QtWidgets.QAction(MainWindow)
        #self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionRandom_Trials = QtWidgets.QAction(MainWindow)
        self.actionRandom_Trials.setObjectName("actionRandom_Trials")
        self.actionRandom_Seed = QtWidgets.QAction(MainWindow)
        self.actionRandom_Seed.setObjectName("actionRandom_Seed")
        self.actionInfer_Splits = QtWidgets.QAction(MainWindow)
        self.actionInfer_Splits.setObjectName("actionInfer_Splits")
        self.actionSSMES_Help = QtWidgets.QAction(MainWindow)
        self.actionSSMES_Help.setObjectName("actionSSMES_Help")
        self.actionSSMES_on_Github = QtWidgets.QAction(MainWindow)
        self.actionSSMES_on_Github.setObjectName("actionSSMES_on_Github")
        self.actionAbout_SSMES = QtWidgets.QAction(MainWindow)
        self.actionAbout_SSMES.setObjectName("actionAbout_SSMES")
        self.actionTerm_Schedule = QtWidgets.QAction(MainWindow)
        self.actionTerm_Schedule.setObjectName("actionTerm_Schedule")
        self.menuFile.addSeparator()
        #self.menuFile.addAction(self.actionOpen)
        #self.menuFile.addAction(self.actionSave_As)
        #self.menuFile.addAction(self.actionSave)
        #self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionSSMES_Help)
        self.menuHelp.addAction(self.actionSSMES_on_Github)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_SSMES)
        self.menuSettings.addAction(self.actionTerm_Schedule)
        self.menuSettings.addAction(self.actionRandom_Trials)
        self.menuSettings.addAction(self.actionRandom_Seed)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SSMES"))
        self.RestrictedSplitDepartmentsLabel.setText(_translate("MainWindow", "Restricted Split Departments"))
        self.FromExcludedButton.setText(_translate("MainWindow", "From Excluded"))
        self.ExcludedCoursesLabel.setText(_translate("MainWindow", "Excluded Courses"))
        self.DataFileButton.setText(_translate("MainWindow", "Choose File"))
        self.DataFileLabel.setText(_translate("MainWindow", "Data File"))
        self.FromRestrictedButton.setText(_translate("MainWindow", "From Restricted"))
        self.CheckBox.setText(_translate("MainWindow", "Infer Split Departments"))
        self.ToDefiniteButton.setText(_translate("MainWindow", "To Definite"))
        self.ExcludedCoursesLoadFileButton.setText(_translate("MainWindow", "Load Data"))
        self.DefiniteSplitDepartmentsLabel.setText(_translate("MainWindow", "Definite Split Departments"))
        self.FromDefiniteButton.setText(_translate("MainWindow", "From Definite"))
        self.LoadDataButton.setText(_translate("MainWindow", "Load Data"))
        self.ExcludedCoursesFileLabel.setText(_translate("MainWindow", "Excluded Courses File"))
        self.CoursesLabel.setText(_translate("MainWindow", "Courses"))
        self.DepartmentsLabel.setText(_translate("MainWindow", "Departments"))
        self.TermLabel.setText(_translate("MainWindow", "Term"))
        self.NumberOfExamDaysLabel.setText(_translate("MainWindow", "Number of Exam Days"))
        self.ToExcludedButton.setText(_translate("MainWindow", "To Excluded"))
        self.ToRestrictedButton.setText(_translate("MainWindow", "To Restricted"))
        self.CreateExamScheduleButton.setText(_translate("MainWindow", "Create Exam Schedule"))
        self.MessageCenterLabel.setText(_translate("MainWindow", "Message Center"))
        self.SSMESLabel.setText(_translate("MainWindow", "School of Science and Math Exam Scheduler"))
        self.ExcludedCoursesFileButton.setText(_translate("MainWindow", "Choose File"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        #self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        #self.actionSave.setText(_translate("MainWindow", "Save"))
        #self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionRandom_Trials.setText(_translate("MainWindow", "Total Random Trials"))
        self.actionRandom_Seed.setText(_translate("MainWindow", "Random Seed"))
        self.actionInfer_Splits.setText(_translate("MainWindow", "Infer Splits"))
        self.actionSSMES_Help.setText(_translate("MainWindow", "SSMES Help"))
        self.actionSSMES_on_Github.setText(_translate("MainWindow", "SSMES on Github"))
        self.actionAbout_SSMES.setText(_translate("MainWindow", "About SSMES"))
        self.actionTerm_Schedule.setText(_translate("MainWindow", "Term Schedule"))


